FROM alpine:3.22

RUN addgroup -g 1000 familybridge && adduser -D -H -u 1000 -G familybridge familybridge
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/familybridge /usr/local/bin/familybridge

USER familybridge
EXPOSE 6773
ENTRYPOINT ["/usr/local/bin/familybridge"]
